FROM docker.io/library/nginx:alpine

COPY frontend/index.html /usr/share/nginx/html/index.html
COPY frontend/style.css /usr/share/nginx/html/style.css
COPY frontend/app.js /usr/share/nginx/html/app.js
COPY frontend/images /usr/share/nginx/html/images
COPY config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
